---
- name: playbook for proxmox hipervisior and VM for AM/ML Edge Platform
  hosts: pvehost12
#  user: ubuntu
#  become: yes
#  connection: ssh
#  debuger: on_failed
#  gather_facs: yes
  tasks:
   - name: Change GRUB config
     ansible.builtin.lineinfile:
       path: "/etc/default/grub"
       regexp: 'GRUB_CMDLINE_LINUX_DEFAULT="(.*)"'
       line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on efifb=off"'
   - name: Update GRUB
     ansible.builtin.command: update-grub
   - name: Get GRUB config
     ansible.builtin.shell: cat /etc/default/grub
     register: grub
   - name: Print the grub output
     ansible.builtin.debug:
       msg: "{{ grub }}"
#   - name: Add the Nvidia drivers to the blacklist to prevent them from being loaded by Proxmox
#     ansible.builtin.lineinfile:
#       path: "/etc/modprobe.d/pve-blacklist.conf"
#       line: "{{driver}}"
#       create: yes
#     ansible.builtin.command: echo {{ item.driver }} >> /etc/modprobe.d/pve-blacklist.conf
   - name: Remove a line
     lineinfile:
       path: "/etc/modprobe.d/pve-blacklist.conf"
       search_string: "{{item.driver}}"
       line: "{{item.driver}}"
     with_items:
       - driver: "blacklist nvidia"
       - driver: "blacklist nouveau"
       - driver: "blacklist radeon"

   - name: get blacklist.conf to variable
     ansible.builtin.command: cat /etc/modprobe.d/pve-blacklist.conf
     register: blacklist
   - name: Print blacklist.conf
     ansible.builtin.debug:
       msg: "{{blacklist}}"
   - name: Update initramfs
     ansible.builtin.command: update-initramfs -u
   - name: Add Virtual Function IO (vfio) kernel modules to load at boot time
     ansible.builtin.command: echo {{ item.variable }} >> /etc/modules
     with_items:
       - variable: "vfio"
       - variable: "vfio_iommu_type1"
       - variable: "vfio_pci"
       - variable: "vfio_virqfd"
   - name: Get modules
     ansible.builtin.shell: cat /etc/modules
     register: modules
   - name: Print the modules output
     ansible.builtin.debug:
       msg: "{{ modules }}"
   - name: Get GeForce RTX address and IDs
     ansible.builtin.command: lspci -n -s 01:00 | awk '{print $3}'
     register: lspci_output
   - name: Print lspci_output
     ansible.builtin.debug:
       msg: "{{lspci_output}}"
   - name: Assign the GeForce RTX to the Virtual Function IO (vfio)
     ansible.builtin.command: echo "options vfio-pci ids={{item.ids}}" > /etc/modprobe.d/vfio.conf
     with_items:
       - ids: lspci_output
   - name: enable IOMMU interrupt remapping
     ansible.builtin.command: echo "options vfio_iommu_type1 allow_unsafe_interrupts=1" > /etc/modprobe.d/iommu_unsafe_interrupts.conf
   - name: Reboot
     ansible.builtin.reboot:
