---
- name: playbook for proxmox hipervisior and VM for AM/ML Edge Platform
  hosts: pvehost12
#  user: ubuntu
#  become: yes
#  connection: ssh
#  debuger: on_failed
#  gather_facs: yes
  tasks:
   - name: Change GRUB config
     ansible.builtin.lineinfile:
       path: "/etc/default/grub"
       regexp: 'GRUB_CMDLINE_LINUX_DEFAULT="(.*)"'
       line: 'GRUB_CMDLINE_LINUX_DEFAULT="quiet intel_iommu=on efifb=off"'
   - name: Update GRUB
     ansible.builtin.command: update-grub
   - name: Get GRUB config
     ansible.builtin.shell: cat /etc/default/grub
     register: grub
   - name: Print the grub output
     ansible.builtin.debug:
       msg: "{{ grub }}"
#
   - name: Check if driver in blacklist
     ansible.builtin.shell: grep -q "{{ item.driver }}" /etc/modprobe.d/pve-blacklist.conf
     register: blacklist_check
     ignore_errors: yes
     changed_when: false
     loop:
       - driver: "blacklist nvidia"
       - driver: "blacklist nouveau"
       - driver: "blacklist radeon"
       - driver: "blacklist nvidiafb"

   - name: Append missing drivers to blacklist
     ansible.builtin.lineinfile:
       path: "/etc/modprobe.d/pve-blacklist.conf"
       line: "{{ item.driver }}"
     when: blacklist_check is succeeded and item not in blacklist_check.results | map(attribute='item.driver') | list
     loop:
       - driver: "blacklist nvidia"
       - driver: "blacklist nouveau"
       - driver: "blacklist radeon"
       - driver: "blacklist nvidiafb"
     changed_when: true

##
   - name: get blacklist.conf to variable
     ansible.builtin.command: cat /etc/modprobe.d/pve-blacklist.conf
     register: blacklist
   - name: Print blacklist.conf
     ansible.builtin.debug:
       msg: "{{blacklist}}"
   - name: Update initramfs
     ansible.builtin.command: update-initramfs -u
#
   - name: Add Virtual Function IO (vfio) kernel modules to load at boot time
     ansible.builtin.shell: grep -q "{{ item }}" /etc/modules
     register: vfio_check
     ignore_errors: yes
     changed_when: false
     loop:
       - "vfio"
       - "vfio_iommu_type1"
       - "vfio_pci"
       - "vfio_virqfd"

   - name: Append vfio modules to /etc/modules if not present
     ansible.builtin.lineinfile:
       path: "/etc/modules"
       line: "{{ item }}"
     when: vfio_check is succeeded and item not in vfio_check.results | map(attribute='cmd') | list
     loop:
       - "vfio"
       - "vfio_iommu_type1"
       - "vfio_pci"
       - "vfio_virqfd"
     changed_when: true
##
   - name: Get modules
     ansible.builtin.shell: cat /etc/modules
     register: modules
   - name: Print the modules output
     ansible.builtin.debug:
       msg: "{{ modules }}"
#
   - name: Get GeForce RTX address and IDs
     ansible.builtin.shell: lspci -n -s 01:00 | awk 'BEGIN { ORS=", " }; {print $3}'
     register: lspci_output_raw
   - name: Process lspci output
     ansible.builtin.set_fact:
       lspci_output: "{{ lspci_output_raw.stdout | regex_replace(', $', '') }}"
   - name: Print lspci_output
     ansible.builtin.debug:
       msg: "{{lspci_output}}"
##
   - name: Create vfio.conf file only when it does not exists
     copy:
       content: ""
       dest: /etc/modprobe.d/vfio.conf
       force: false
       group: sys
       owner: root
       mode: 0555
   - name: Assign the GeForce RTX to the Virtual Function IO (vfio)
     ansible.builtin.lineinfile:
       path: "/etc/modprobe.d/vfio.conf"
       search_string: "{{item.ids}}"
       line: options vfio-pci ids="{{item.ids}}"
     with_items:
       - ids: "{{lspci_output}}"
   - name: Create iommu_unsafe_interrupts.conf.conf file only when it does not exists
     copy:
       content: ""
       dest: /etc/modprobe.d/iommu_unsafe_interrupts.conf
       force: false
       group: sys
       owner: root
       mode: 0555
   - name: enable IOMMU interrupt remapping
     ansible.builtin.lineinfile:
       path: "/etc/modprobe.d/iommu_unsafe_interrupts.conf"
       search_string: "{{item.variable}}"
       line: "{{item.variable}}"
     with_items:
       - variable: "options vfio_iommu_type1 allow_unsafe_interrupts=1"
   - name: Reboot
     ansible.builtin.reboot:
