- name: Copy file from local to remote VM
  hosts: pvevms
  tasks:
   - name: Copy test file to VM location
     ansible.builtin.copy: 
       src: /home/semaphore/files/orange_alpr_app_latest.tar
       dest: /root/orange_alpr_app_latest.tar
       owner: 0
       group: 0
       mode: '0755'
   - name: Load the docker image
     ansible.builtin.command: sudo docker load -i /root/orange_alpr_app_latest.tar
     register: dockeroutput
   - name: Print the docker output
     ansible.builtin.debug:
       msg: "{{ dockeroutput }}"
     when: dockeroutput is defined
   - name: Bring up docker compose
     ansible.builtin.command: sudo docker compose -f /home/ubuntu/ai_edge/docker-compose.yml up -d
     register: dockercompose
   - name: Print the docker compose output
     ansible.builtin.debug:
       msg: "{{ dockercompose }}"
     when: dockercompose is defined
