- name: Create datastore in PBS with user and privileges
  hosts: "{{ variable_host | default('pbs') }}"
  tasks:
  - name: Create new PBS datastore with given name and path
    ansible.builtin.command: "proxmox-backup-manager datastore create {{ datastore }} /iguard/{{ datastore | lower }}"
    register: pbm_datastore_create_output
    failed_when: "(pbm_datastore_create_output.stderr | length > 0) and 'already exists' not in pbm_datastore_create_output.stderr"
  - name: Create a user for given datastore
    ansible.builtin.command: "proxmox-backup-manager user create {{ datastore }}@pbs --password {{ user_password }}"
    register: pbm_user_create_output
    when: "pbm_datastore_create_output.stderr | length > 0"
    failed_when: "(pbm_user_create_output.stderr | length > 0) and 'already exists' not in pbm_user_create_output.stderr"
  - name: Give a role to the new user
    ansible.builtin.command: "proxmox-backup-manager acl update /iguard/{{ datastore }} DatastoreBackup --auth-id {{ datastore }}@pbs
