- name: Add PBS with basic VM snapshot to PVE node
  hosts: "{{ variable_host | default('pvehosts') }}"
  tasks:
  - name: Get all current storage
    ansible.builtin.command: pvesh get storage -o json
    register: storage_json
  - name: Degub print
    meta: end_play
    when: item.fingerprint is defined and item.fingerprint == fingerprint
    with_items:
      - "{{ storage_json.stdout }}"
