- name: Add PBS with basic VM snapshot to PVE node
  hosts: "{{ variable_host | default('pvehosts') }}"
  tasks:
  - name: Get all current storage
    ansible.builtin.command: pvesh get storage --output-format=json
      register: storage_json
  - name: Print return information from the previous task
    ansible.builtin.debug:
      var: storage_json
      
  # - name: Loop over data and continue if string was found.
  #   fail:
  #     msg: "The PBS storage with fingerprint of '{{ fingerprint }}' was not found.
  #   when: fingerprint not in item
  #   loop: "{{ storage_json }}"
