- name: Add PBS with basic VM snapshot to PVE node
  hosts: "{{ variable_host | default('pvehosts') }}"
  tasks:
  - name: Get all current storage
    ansible.builtin.command: pvesh get storage -o json
    register: storage_json
  - name: Get PBS storage
    vars:
      - pbs_item: "{{ storage_json.stdout | from_json | selectattr('type','==','pbs') }}"
    debug:
      msg: "{{ pbs_item }}"
