- ansible.builtin.import_playbook: create_datastore.yml
  vars:
    variable_host: "pbs"
    datastore: "{{ datastore }}"
    user_password: "{{ user_password }}"
- ansible.builtin.import_playbook: pbs_repo.yml
  vars:
    variable_host: "{{ variable_pve }}"
    username: "{{ datastore }}"
    password: "{{ user_password }}"
    fingerprint: "{{ fingerprint }}"
    server: "{{ server }}"
    datastore: "{{ datastore }}"
