- name: Add PBS with basic VM snapshot to PVE node
  hosts: "{{ variable_host | default('pvehosts') }}"
  tasks:
  - name: Create new PBS storage on host with given vars
    ansible.builtin.command: "pvesm add pbs repo_pbs -username {{ username }} -password {{ password }} -fingerprint {{ fingerprint }} -server {{ server }} -datastore {{ datastore }}"
    register: pvesm_output
    ignore_errors: yes
  - name: Debug PBS definition output
    ansible.builtin.debug:
      var: pvesm_output
