- name: Add PBS with basic VM snapshot to PVE node
  hosts: "{{ variable_host | default('pvehosts') }}"
  tasks:
  - name: Get all current storage
    ansible.builtin.command: pvesh get storage -o json
    register: storage_json
  - name: Check for PBS storage
    ansible.builtin.meta: end_play
    when: pbs_item is defined and (pbs_item | length > 0)
    vars:
      - pbs_item: "{{ storage_json.stdout | from_json | selectattr('type','==','pbs') }}"
