- name: Add PBS with basic VM snapshot to PVE node
  hosts: "{{ variable_host | default('pvehosts') }}"
  tasks:
  - name: Get all current storage
    ansible.builtin.command: pvesh get storage -o json
    register: storage_json
  - name: Print return information from the previous task
    ansible.builtin.debug:
      var: storage_json
