- name: List nodes on the PVE
  hosts: pvehosts
  tasks:
   - name: Return pvenodes to registered var
     ansible.builtin.command: pvesh get /nodes --output-format=yaml
     register: pvenodes
   - name: Print the current user
     ansible.builtin.debug:
       msg: "Found nodes: {{ pvenodes.stdout | from_yaml}}"
     when: pvenodes is defined
