- name: List nodes on the PVE
  hosts: pvehosts
  tasks:
   - name: Return pvenodes to registered var
     ansible.builtin.command: pvesh get /nodes --output-format=yaml
     register: pvenodes
   - name: Display all cluster names
     ansible.builtin.debug:
       var: item
     loop: "{{ pvenodes | community.general.json_query('[*].node') }}"
