- name: Tell which user is accessed
  hosts: pvehosts
  tasks:
   - name: Return whoami to registered var
     ansible.builtin.command: whoami
     register: curruser
   - name: Print the current user
     ansible.builtin.debug:
       msg: Currently logged in as {{ curruser }}
     when: curruser is defined
